apiVersion: v1
kind: Service
metadata:
  name: {{ include "bedindustries-microservice-group.fullname" . }}
  labels:
    {{- include "bedindustries-microservice-group.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{range .Values.service.containers }}
    - port: {{ .ingressPort }}
      targetPort: {{.containerPort}}
      protocol: TCP
      name: {{.name}}
    {{- end }}
  selector:
    {{- include "bedindustries-microservice-group.selectorLabels" . | nindent 4 }}
