affinity: {}
autoscaling:
  enabled: true
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
deployment:
  containerPort: 80
  enable_healthcheck: true
  image: wordpress
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred
  livenessProbe:
    failureThreshold: 10
    httpGet:
      path: /wp-admin/setup-config.php
      port: 80
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
  progressDeadlineSeconds: 300
  readinessProbe:
    failureThreshold: 10
    httpGet:
      path: /wp-admin/setup-config.php
      port: 80
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  strategy:
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 0
    type: RollingUpdate
environment_variables:
  EXAMPLE_VARIABLE: This is just an example.
fullnameOverride: ""
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  enabled: true
  hosts:
    - host: wordpress.sonicx.io
      paths:
        - type: Prefix
          value: /
    - host: wordpress.bedindustries.com
      paths:
        - type: Prefix
          value: /
  tls:
    [
    {
      hosts: [ wordpress.sonicx.io ],
      secretName: wordpress-sonicx-io
    }
    ]
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  port: 80

persistence:
  enabled: true
  ## Data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  mountPath: /worker
  accessMode: ReadWriteOnce
  size: 2Gi
serviceAccount:
  annotations: {}
  create: false
  name: ""
tolerations: []
topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: application
  whenUnsatisfiable: DoNotSchedule
