apiVersion: v1
kind: Service
metadata:
  name: {{ include "dark-knight-router.fullname" . }}
  labels:
    {{- include "dark-knight-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30047
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dark-knight-router.selectorLabels" . | nindent 4 }}
